--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AID-LEARNING/RolesManagerScore
branches:
  - stable
  - beta
projects:
  RolesManagerScore:
    path: ""
    icon: ""
    lint:
      phpstan: false
    libs:
      - src: AID-LEARNING/ExtraEvent/libEventAttribute
        version: ^1.0.2

...
