name: RoleManagerScore
authors:
  - SenseiTarzan
version: 1.0.0
main: SenseiTarzan\RoleManagerScore\Main
api: 5.0.0
description: A plugin implementing some basic tags for ScoreHud.
depend:
  - "ScoreHud"
  - "RoleManager"